### PR TITLE
Set stack limit to unlimited

### PR DESCRIPTION
**Pull request by toutoumeteo**
git clone was lacking resource with default stack size.

### CODE REVIEW

**Comment by neishm** [comment]
Sounds like a reasonable modification.  Out of curiosity, what repository was causing a problem with the stack size??

**Comment by toutoumeteo** [comment]
vgrid

**Comment by neishm** [comment]
Unfortunately I'm unable to reproduce the stack problem on my particular machine, but there's [some indication](https://groups.google.com/d/msg/docker-user/T45Kc9vD804/_15hLC9z-oEJ) that docker inherits ulimits from the host (although this is very poorly documented).  So `git clone` could work on one host machine and not another.  Your update should be a good way to deal with this.

**Comment by toutoumeteo** [comment]
I think you are right (it seems that you are right often ;-)). The stack size on my docker session is limited to 8192. This is the limit on my MacBook terminal.


root@ff215c532110:/# ulimit -s
8192
root@ff215c532110:/# exit
exit
MacBook-Pro-de-Andre:~ andre$ ulimit -s
8192

**Comment by toutoumeteo** [comment]
Hi Mike,

K. Onu told me that you have a repository for GEM, Maestro, rmnlib in Docker. Impressive! I am interested to play with this. Could you tell me where the repo is?

Regards

André

**Comment by neishm** [comment]
Hi André,

The repository is on the intranet at https://gccode.ssc-spc.gc.ca/neishm/gem-docker.  I'm hoping to move it to GitHub at some point, once two of the dependencies (`gem-mod` and `gem-ref`) are publicly available (see https://gitlab.science.gc.ca/MIG/gem-mod/issues/1).

Cheers,
Mike

**Pull request merged**
